---
title: "Oscar Nomination Sentiment"
author: "Lucy D'Agostino McGowan"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning = FALSE}
library(rtweet)
library(tidytext)
library(tidymodels)
library(tidyverse)
```

```{r, eval = FALSE}
tweets <- search_tweets("#OscarNominations", n = 4000)
tweets <- tweets %>%
  select(user_id, status_id, created_at, screen_name, text, is_quote, is_retweet,
         favorite_count, retweet_count)
write_csv(tweets, "data/tweets.csv")
```

```{r}
tweets <- read_csv("data/tweets.csv")
```

```{r}
sentiments <- tweets %>%
  unnest_tokens(word, text) %>%
  inner_join(get_sentiments("bing"), by = "word") %>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()
```

```{r sentiment-figure}
sentiments %>%
  group_by(sentiment) %>%
  top_n(5, wt = n) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(y = "Contribution to sentiment",
       x = NULL) +
  coord_flip()
```

